add conditional parameter for ClusterWS to autoConnect the Socket
goriunov/ClusterWS-Client-JS pull request #54
Opened 2019-01-08 04:54 UTC by ramjak

### Submitting

- [ ] Bug fix
- [x] Feature
- [ ] Other

### Details
add a conditional parameter for ClusterWS to autoConnect the Socket

2019-01-08 08:52 UTC, goriunov requested changes
Thank you for pull request there are few small things which needs to be adjusted but overall looks great :)

2019-01-08 08:52 UTC, goriunov commented on src/index.ts
> +  public start(): void {
I think rename method to  `connect` would be better as in Java and Swift we use `connect`.

2019-01-08 08:52 UTC, goriunov commented on src/utils/types.ts
> +  autoConnect?: boolean;
Can you move this line under `url` :)

2019-01-08 08:52 UTC, goriunov commented on src/index.ts
> +      console.log('The socket has already been created');
Can you use `logError` function from utils.

2019-01-08 08:52 UTC, goriunov commented on src/index.ts
> +    this.hasStarted = true
I think this one can be moved to the top of `create` function

2019-01-08 08:52 UTC, goriunov commented on src/index.ts
> +  private hasStarted: boolean = false
I think `hasStartedConnection` name suites more in this case.

2019-01-08 09:37 UTC, ramjak commented
this one is good?

2019-01-08 11:27 UTC, goriunov approved these changes

2019-01-08 11:27 UTC, goriunov commented
Looks good :) I will merge it soon

2019-01-10 03:28 UTC, goriunov commented on src/index.ts
> +      autoConnect: typeof configurations.autoConnect === 'undefined' ? true : configurations.autoConnect,
i think you can handle it with just `configurations.autoConnect !== false`

2019-01-11 07:11 UTC, ramjak commented on src/index.ts
> +      autoConnect: typeof configurations.autoConnect === 'undefined' ? true : configurations.autoConnect,
hmm, I never thought of that

2019-01-11 07:19 UTC, goriunov commented
Thanks looks good :)

2019-01-11 07:19 UTC, merged